server:
  port: 8081
  tomcat:
    threads:
      max: 500
      min-spare: 50

spring:
  application:
    name: microservice-in-1

  datasource:
    url: jdbc:postgresql://localhost:5432/payment_hub_db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 3000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 50

# ------------------------------------------------
# Custom RabbitMQ Config (USED IN CODE)
# ------------------------------------------------
rabbitmq:
  exchange: payment.hub.exchange
  queues:
    router: router.queue
    from-ms2: ms1.response.queue   # ✅ THIS FIXES YOUR ERROR
  routing-keys:
    router: router.txn
    response: ms1.response.key

# JWT
app:
  jwt-secret: your-very-strong-256-bit-secret-key-change-this
  jwt-expiration-seconds: 86400

# Encryption
encryption:
  client-aes-key: "MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI="

# Logging
logging:
  level:
    com.paymenthub.ms1: DEBUG
    org.springframework: INFO
    org.springframework.amqp: DEBUG